# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4b86cedc04b0d5715e472eaee508b0c2108b9f48eb2bb0b358af1845774b894e9821ac24d79265a4b37a45a2fd4c2c71c788316fde4471338e502a5cf98af9a
  multichain: 
   username: <%= ENV["MULTICHAIN_USERNAME"] %>
   password: <%= ENV["MULTICHAIN_PASSWORD"] %> 
   host: <%= ENV["MULTICHAIN_HOST"] %>
   port: <%= ENV["MULTICHAIN_PORT"] %>
   ssl: <%= ENV["MULTICHAIN_SSL"] %>

test:
  secret_key_base: 11593c9ea10efb4f3118a72c49d62d5cc9a833dd83e4fa36391c90c05a9f35e37559d02329a6e84c46e3087e3a2584d6741d43d694c8308bdbe96c081243f257
  multichain: 
   username: <%= ENV["MULTICHAIN_USERNAME"] %>
   password: <%= ENV["MULTICHAIN_PASSWORD"] %> 
   host: <%= ENV["MULTICHAIN_HOST"] %>
   port: <%= ENV["MULTICHAIN_PORT"] %>
   ssl: <%= ENV["MULTICHAIN_SSL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  multichain: 
   username: <%= ENV["MULTICHAIN_USERNAME"] %>
   password: <%= ENV["MULTICHAIN_PASSWORD"] %>   
   host: <%= ENV["MULTICHAIN_HOST"] %>
   port: <%= ENV["MULTICHAIN_PORT"] %>
   ssl: <%= ENV["MULTICHAIN_SSL"] %>